# Generated by Django 2.2.4 on 2020-12-16 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('like_users', models.ManyToManyField(null=True, related_name='favorite_books', to='login_register.User')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='login_register.User')),
            ],
        ),
    ]
