# Generated by Django 2.2.4 on 2020-12-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='like_users',
            field=models.ManyToManyField(related_name='favorite_books', to='login_register.User'),
        ),
    ]
